#pragma checksum "..\..\..\Views\Seguridad\UserCollectionView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A0683B25ECD96D043D855EB5D87D0E1FB4147353"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.Mvvm;
using DevExpress.Mvvm.UI;
using DevExpress.Mvvm.UI.Interactivity;
using DevExpress.Mvvm.UI.Interactivity.TypedStyles;
using DevExpress.Mvvm.UI.ModuleInjection;
using DevExpress.Mvvm.UI.TypedStyles;
using DevExpress.Mvvm.ViewModel;
using DevExpress.Xpf.Bars;
using DevExpress.Xpf.Bars.TypedStyles;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.ConditionalFormatting.TypedStyles;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.DataSources.TypedStyles;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.Serialization.TypedStyles;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.Core.ServerMode.TypedStyles;
using DevExpress.Xpf.Core.TypedStyles;
using DevExpress.Xpf.Docking;
using DevExpress.Xpf.Docking.Base;
using DevExpress.Xpf.Docking.TypedStyles;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DataPager.TypedStyles;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.DateNavigator.TypedStyles;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.ExpressionEditor.TypedStyles;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Filtering.TypedStyles;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Flyout.TypedStyles;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.Popups.Calendar.TypedStyles;
using DevExpress.Xpf.Editors.Popups.TypedStyles;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.RangeControl.TypedStyles;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Settings.TypedStyles;
using DevExpress.Xpf.Editors.TypedStyles;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Editors.Validation.TypedStyles;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.ConditionalFormatting;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.LookUp.TypedStyles;
using DevExpress.Xpf.Grid.TreeList;
using DevExpress.Xpf.Grid.TreeList.TypedStyles;
using DevExpress.Xpf.Grid.TypedStyles;
using DevExpress.Xpf.Ribbon;
using DevExpress.Xpf.Ribbon.TypedStyles;
using NextBO.Wpf;
using NextBO.Wpf.Services;
using NextBO.Wpf.ViewModels;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Automation.TypedStyles;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Primitives.TypedStyles;
using System.Windows.Controls.TypedStyles;
using System.Windows.Data;
using System.Windows.Data.TypedStyles;
using System.Windows.Documents;
using System.Windows.Documents.TypedStyles;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Input.TypedStyles;
using System.Windows.Markup;
using System.Windows.Markup.TypedStyles;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Animation.TypedStyles;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Media.TypedStyles;
using System.Windows.Navigation;
using System.Windows.Navigation.TypedStyles;
using System.Windows.Shapes;
using System.Windows.Shapes.TypedStyles;
using System.Windows.Shell;
using System.Windows.TypedStyles;


namespace NextBO.Wpf.Views {
    
    
    /// <summary>
    /// UserCollectionView
    /// </summary>
    public partial class UserCollectionView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 229 "..\..\..\Views\Seguridad\UserCollectionView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarSubItem DataPaneBarSubItem;
        
        #line default
        #line hidden
        
        
        #line 233 "..\..\..\Views\Seguridad\UserCollectionView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarCheckItem HorizontalViewBarCheckItem;
        
        #line default
        #line hidden
        
        
        #line 241 "..\..\..\Views\Seguridad\UserCollectionView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarCheckItem VerticalViewBarCheckItem;
        
        #line default
        #line hidden
        
        
        #line 249 "..\..\..\Views\Seguridad\UserCollectionView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarCheckItem IsDataPaneVisibleBarCheckItem;
        
        #line default
        #line hidden
        
        
        #line 261 "..\..\..\Views\Seguridad\UserCollectionView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem ReverseSortBarButtonItem;
        
        #line default
        #line hidden
        
        
        #line 273 "..\..\..\Views\Seguridad\UserCollectionView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem AddColumnsBarButtonItem;
        
        #line default
        #line hidden
        
        
        #line 278 "..\..\..\Views\Seguridad\UserCollectionView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarSubItem ExpandCollapseBarSubItem;
        
        #line default
        #line hidden
        
        
        #line 312 "..\..\..\Views\Seguridad\UserCollectionView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl tableViewGridControl;
        
        #line default
        #line hidden
        
        
        #line 329 "..\..\..\Views\Seguridad\UserCollectionView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal NextBO.Wpf.GridSaveLayoutBehavior SerializeHelper;
        
        #line default
        #line hidden
        
        
        #line 335 "..\..\..\Views\Seguridad\UserCollectionView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.TableView UserTableView;
        
        #line default
        #line hidden
        
        
        #line 429 "..\..\..\Views\Seguridad\UserCollectionView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl cardViewGridControl;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.2.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/NextBO.Wpf;component/views/seguridad/usercollectionview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\Seguridad\UserCollectionView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.2.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.2.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.DataPaneBarSubItem = ((DevExpress.Xpf.Bars.BarSubItem)(target));
            return;
            case 2:
            this.HorizontalViewBarCheckItem = ((DevExpress.Xpf.Bars.BarCheckItem)(target));
            return;
            case 3:
            this.VerticalViewBarCheckItem = ((DevExpress.Xpf.Bars.BarCheckItem)(target));
            return;
            case 4:
            this.IsDataPaneVisibleBarCheckItem = ((DevExpress.Xpf.Bars.BarCheckItem)(target));
            return;
            case 5:
            this.ReverseSortBarButtonItem = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 6:
            this.AddColumnsBarButtonItem = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 7:
            this.ExpandCollapseBarSubItem = ((DevExpress.Xpf.Bars.BarSubItem)(target));
            return;
            case 8:
            this.tableViewGridControl = ((DevExpress.Xpf.Grid.GridControl)(target));
            return;
            case 9:
            this.SerializeHelper = ((NextBO.Wpf.GridSaveLayoutBehavior)(target));
            return;
            case 10:
            this.UserTableView = ((DevExpress.Xpf.Grid.TableView)(target));
            return;
            case 11:
            this.cardViewGridControl = ((DevExpress.Xpf.Grid.GridControl)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

