#pragma checksum "..\..\Views\BaseView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0DE335918B3FAE5762DE831493040E5AC1AF80A1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.DemoData;
using DevExpress.Mvvm;
using DevExpress.Mvvm.UI;
using DevExpress.Mvvm.UI.Interactivity;
using DevExpress.Mvvm.UI.Interactivity.TypedStyles;
using DevExpress.Mvvm.UI.ModuleInjection;
using DevExpress.Mvvm.UI.TypedStyles;
using DevExpress.Mvvm.ViewModel;
using DevExpress.Xpf.Accordion;
using DevExpress.Xpf.Accordion.TypedStyles;
using DevExpress.Xpf.Bars;
using DevExpress.Xpf.Bars.TypedStyles;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.ConditionalFormatting.TypedStyles;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.DataSources.TypedStyles;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.Serialization.TypedStyles;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.Core.ServerMode.TypedStyles;
using DevExpress.Xpf.Core.TypedStyles;
using DevExpress.Xpf.DXBinding;
using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.DemoBase.DataClasses;
using DevExpress.Xpf.DemoBase.Helpers;
using DevExpress.Xpf.Docking;
using DevExpress.Xpf.Docking.Base;
using DevExpress.Xpf.Docking.TypedStyles;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DataPager.TypedStyles;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.DateNavigator.TypedStyles;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.ExpressionEditor.TypedStyles;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Filtering.TypedStyles;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Flyout.TypedStyles;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.Popups.Calendar.TypedStyles;
using DevExpress.Xpf.Editors.Popups.TypedStyles;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.RangeControl.TypedStyles;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Settings.TypedStyles;
using DevExpress.Xpf.Editors.TypedStyles;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Editors.Validation.TypedStyles;
using DevExpress.Xpf.LayoutControl;
using DevExpress.Xpf.LayoutControl.TypedStyles;
using DevExpress.Xpf.Navigation;
using DevExpress.Xpf.Navigation.TypedStyles;
using DevExpress.Xpf.Ribbon;
using DevExpress.Xpf.Ribbon.TypedStyles;
using DevExpress.Xpf.TypedStyles;
using DevExpress.Xpf.WindowsUI;
using DevExpress.Xpf.WindowsUI.Navigation;
using DevExpress.Xpf.WindowsUI.Navigation.TypedStyles;
using DevExpress.Xpf.WindowsUI.TypedStyles;
using NextBO.Wpf;
using NextBO.Wpf.Common.View;
using NextBO.Wpf.Controls;
using NextBO.Wpf.ViewModels;
using NextBO.Wpf.Views;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Automation.TypedStyles;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Primitives.TypedStyles;
using System.Windows.Controls.Ribbon;
using System.Windows.Controls.TypedStyles;
using System.Windows.Data;
using System.Windows.Data.TypedStyles;
using System.Windows.Documents;
using System.Windows.Documents.TypedStyles;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Input.TypedStyles;
using System.Windows.Markup;
using System.Windows.Markup.TypedStyles;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Animation.TypedStyles;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Media.TypedStyles;
using System.Windows.Navigation;
using System.Windows.Navigation.TypedStyles;
using System.Windows.Shapes;
using System.Windows.Shapes.TypedStyles;
using System.Windows.Shell;
using System.Windows.TypedStyles;


namespace NextBO.Wpf.Views {
    
    
    /// <summary>
    /// BaseView
    /// </summary>
    public partial class BaseView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 46 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Core.DXSplashScreenService SplashScreenService;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Core.WindowedDocumentUIService SignleObjectDocumentManagerService;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Mvvm.UI.DispatcherService FinishModuleChangingDispatcherService;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Core.DialogService LoginDialogService;
        
        #line default
        #line hidden
        
        
        #line 124 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Core.WindowedDocumentUIService AnalysisWindowedDocumentUIService;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Core.DialogService FilterDialogService;
        
        #line default
        #line hidden
        
        
        #line 217 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Ribbon.RibbonControl ribbonControl;
        
        #line default
        #line hidden
        
        
        #line 221 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Ribbon.BackstageViewControl backStageView;
        
        #line default
        #line hidden
        
        
        #line 292 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal NextBO.Wpf.Common.View.BackstageDocumentPreviewReportService ExportService;
        
        #line default
        #line hidden
        
        
        #line 296 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal NextBO.Wpf.Common.View.BackstageDocumentPreviewReportService PrintService;
        
        #line default
        #line hidden
        
        
        #line 359 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarCheckItem IsFilterPaneNormalBarCheckItem;
        
        #line default
        #line hidden
        
        
        #line 362 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarCheckItem IsFilterPaneMinimizedBarCheckItem;
        
        #line default
        #line hidden
        
        
        #line 365 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarCheckItem IsFilterPaneOffBarCheckItem;
        
        #line default
        #line hidden
        
        
        #line 372 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.DemoBase.Helpers.ThemesBarSplitButtonItem themesItem;
        
        #line default
        #line hidden
        
        
        #line 379 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.DemoBase.Helpers.BarSplitItemDemoThemeSelectorBehavior behavior;
        
        #line default
        #line hidden
        
        
        #line 404 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Ribbon.RibbonStatusBarControl ribbonStatusBarControl;
        
        #line default
        #line hidden
        
        
        #line 422 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Docking.DockLayoutManager dockLayoutManager;
        
        #line default
        #line hidden
        
        
        #line 430 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Docking.DockingDocumentUIService WorkspaceDocumentManagerService;
        
        #line default
        #line hidden
        
        
        #line 455 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Accordion.AccordionControl accordion;
        
        #line default
        #line hidden
        
        
        #line 547 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.WindowsUI.Navigation.FrameDocumentUIService FrameDocumentManagerService;
        
        #line default
        #line hidden
        
        
        #line 549 "..\..\Views\BaseView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Core.DXSplashScreenService WaitScreenService;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.2.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/NextBO.Wpf;component/views/baseview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\Views\BaseView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.2.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.2.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SplashScreenService = ((DevExpress.Xpf.Core.DXSplashScreenService)(target));
            return;
            case 2:
            this.SignleObjectDocumentManagerService = ((DevExpress.Xpf.Core.WindowedDocumentUIService)(target));
            return;
            case 3:
            this.FinishModuleChangingDispatcherService = ((DevExpress.Mvvm.UI.DispatcherService)(target));
            return;
            case 4:
            this.LoginDialogService = ((DevExpress.Xpf.Core.DialogService)(target));
            return;
            case 5:
            this.AnalysisWindowedDocumentUIService = ((DevExpress.Xpf.Core.WindowedDocumentUIService)(target));
            return;
            case 6:
            this.FilterDialogService = ((DevExpress.Xpf.Core.DialogService)(target));
            return;
            case 7:
            this.ribbonControl = ((DevExpress.Xpf.Ribbon.RibbonControl)(target));
            return;
            case 8:
            this.backStageView = ((DevExpress.Xpf.Ribbon.BackstageViewControl)(target));
            return;
            case 9:
            this.ExportService = ((NextBO.Wpf.Common.View.BackstageDocumentPreviewReportService)(target));
            return;
            case 10:
            this.PrintService = ((NextBO.Wpf.Common.View.BackstageDocumentPreviewReportService)(target));
            return;
            case 11:
            this.IsFilterPaneNormalBarCheckItem = ((DevExpress.Xpf.Bars.BarCheckItem)(target));
            return;
            case 12:
            this.IsFilterPaneMinimizedBarCheckItem = ((DevExpress.Xpf.Bars.BarCheckItem)(target));
            return;
            case 13:
            this.IsFilterPaneOffBarCheckItem = ((DevExpress.Xpf.Bars.BarCheckItem)(target));
            return;
            case 14:
            this.themesItem = ((DevExpress.Xpf.DemoBase.Helpers.ThemesBarSplitButtonItem)(target));
            return;
            case 15:
            this.behavior = ((DevExpress.Xpf.DemoBase.Helpers.BarSplitItemDemoThemeSelectorBehavior)(target));
            return;
            case 16:
            this.ribbonStatusBarControl = ((DevExpress.Xpf.Ribbon.RibbonStatusBarControl)(target));
            return;
            case 17:
            this.dockLayoutManager = ((DevExpress.Xpf.Docking.DockLayoutManager)(target));
            return;
            case 18:
            this.WorkspaceDocumentManagerService = ((DevExpress.Xpf.Docking.DockingDocumentUIService)(target));
            return;
            case 19:
            this.accordion = ((DevExpress.Xpf.Accordion.AccordionControl)(target));
            return;
            case 20:
            this.FrameDocumentManagerService = ((DevExpress.Xpf.WindowsUI.Navigation.FrameDocumentUIService)(target));
            return;
            case 21:
            this.WaitScreenService = ((DevExpress.Xpf.Core.DXSplashScreenService)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

